apiVersion: batch/v1
kind: Job
metadata:
  name: rdkafka-producer
  namespace:
  labels:
    run: rdkafka-producer
spec:
  template:
    metadata:
      name: rdkafka-producer
    spec:
      containers:
        - name: rdkafka-producer
          image: richardfrick/rdkafka:0.11.4
          command: ["/usr/local/bin/producer.sh"]
          env:
          - name: BROKER
            value: ""
          - name: TOPIC
            value: ""
          - name: GROUP
            value: "rdkafkatestconsumer"
          - name: MECHANISM
            value: "PLAIN"
          - name: SECURITY_PROTOCOL
            value: "sasl_ssl"
          - name: SASL_USER
            value: ""
          - name: SASL_PASS
            value: ""
          - name: FROM
            value: "end"
          - name: MESSAGE_COUNT
            value: "100"
          - name: MESSAGE_SIZE
            value: "100"
          - name : MESSAGE_RATE
            value: "100"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
      restartPolicy: Never

